In [72]:
import os
#Data handling
import pandas as pd
import numpy as np
import datetime
#Data Visualization
import matplotlib as mpl
import matplotlib.pyplot as plt
# use the inline backend to generate the plots within the browser
%matplotlib inline

In [17]:
#Loading datasets

df_beauty=pd.read_json('../data/ref/All_Beauty_5.json', lines=True)
df_appliances=pd.read_json('../data/ref/Appliances_5.json', lines=True)
meta_data=pd.read_json('../data/ref/meta_data.json', lines=True)

# Meta Data cleaning

In [18]:
meta_data.head()

,description,title,image,brand,rank,main_cat,date,asin,feature,tech1,also_buy,price,also_view,tech2,details,similar_item
0,[Brand new. Still in factory-sealed plastic.],Kelby Training DVD: The Adobe Photoshop CS5 7-...,[https://images-na.ssl-images-amazon.com/image...,Kelby Training,"[>#654,681 in Electronics (See Top 100 in Elec...",Computers,2011-12-02,0321732960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,[If you're already a Photoshop user and want a...,Kelby Training DVD: Adobe Photoshop CS5 Power ...,[https://images-na.ssl-images-amazon.com/image...,Kelby Training,"[>#830,165 in Electronics (See Top 100 in Elec...",Computers,2011-11-07,0321735722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,[School To Home Notes: Note From the Teacher!\...,TEACHERS FRIEND NOTE FROM THE TEACHER SCHOOL T...,[https://images-na.ssl-images-amazon.com/image...,TEACHERS FRIEND,"[>#1,233,887 in Electronics (See Top 100 in El...",Computers,2007-06-06,0439651859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,[Dooqi is a young brand specializing in high-e...,"[3-pack]Ipad Mini Screen Protector, Dooqi Scre...",[https://images-na.ssl-images-amazon.com/image...,dooqi,"[>#454,595 in Electronics (See Top 100 in Elec...",Computers,2014-12-05,0545729971,"[Hard coated for Scratch Proof (Hardness: 4H),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[Cover for Nook HD],Hd+ Cheetah Cover- Nook,NaN,Nook,"[>#85,661 in Computers & Accessories (See top ...",Computers,2013-09-11,0594450284,[Cheetah cover],"{'Brand Name': 'Nook', 'Item Weight': '1 pound...",NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#Converting the list for images, rank and description
meta_data['description']=meta_data['description'].apply(lambda x: x[0] if isinstance(x,list) else x)
meta_data['image']=meta_data['image'].apply(lambda x: x[0] if isinstance(x,list) else x)
meta_data['rank']=meta_data['rank'].apply(lambda x: x[0] if isinstance(x,list) else x)

In [20]:
meta_data.head()

,description,title,image,brand,rank,main_cat,date,asin,feature,tech1,also_buy,price,also_view,tech2,details,similar_item
0,Brand new. Still in factory-sealed plastic.,Kelby Training DVD: The Adobe Photoshop CS5 7-...,https://images-na.ssl-images-amazon.com/images...,Kelby Training,">#654,681 in Electronics (See Top 100 in Elect...",Computers,2011-12-02,0321732960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,If you're already a Photoshop user and want a ...,Kelby Training DVD: Adobe Photoshop CS5 Power ...,https://images-na.ssl-images-amazon.com/images...,Kelby Training,">#830,165 in Electronics (See Top 100 in Elect...",Computers,2011-11-07,0321735722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,School To Home Notes: Note From the Teacher!\n...,TEACHERS FRIEND NOTE FROM THE TEACHER SCHOOL T...,https://images-na.ssl-images-amazon.com/images...,TEACHERS FRIEND,">#1,233,887 in Electronics (See Top 100 in Ele...",Computers,2007-06-06,0439651859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dooqi is a young brand specializing in high-en...,"[3-pack]Ipad Mini Screen Protector, Dooqi Scre...",https://images-na.ssl-images-amazon.com/images...,dooqi,">#454,595 in Electronics (See Top 100 in Elect...",Computers,2014-12-05,0545729971,"[Hard coated for Scratch Proof (Hardness: 4H),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cover for Nook HD,Hd+ Cheetah Cover- Nook,NaN,Nook,">#85,661 in Computers & Accessories (See top 100)",Computers,2013-09-11,0594450284,[Cheetah cover],"{'Brand Name': 'Nook', 'Item Weight': '1 pound...",NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Convert image into a categorical indicating variable
meta_data['image']=meta_data['image'].apply(lambda x: 1 if isinstance(x,str) and 'https' in x else 0)
meta_data.head()

,description,title,image,brand,rank,main_cat,date,asin,feature,tech1,also_buy,price,also_view,tech2,details,similar_item
0,Brand new. Still in factory-sealed plastic.,Kelby Training DVD: The Adobe Photoshop CS5 7-...,1,Kelby Training,">#654,681 in Electronics (See Top 100 in Elect...",Computers,2011-12-02,0321732960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,If you're already a Photoshop user and want a ...,Kelby Training DVD: Adobe Photoshop CS5 Power ...,1,Kelby Training,">#830,165 in Electronics (See Top 100 in Elect...",Computers,2011-11-07,0321735722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,School To Home Notes: Note From the Teacher!\n...,TEACHERS FRIEND NOTE FROM THE TEACHER SCHOOL T...,1,TEACHERS FRIEND,">#1,233,887 in Electronics (See Top 100 in Ele...",Computers,2007-06-06,0439651859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dooqi is a young brand specializing in high-en...,"[3-pack]Ipad Mini Screen Protector, Dooqi Scre...",1,dooqi,">#454,595 in Electronics (See Top 100 in Elect...",Computers,2014-12-05,0545729971,"[Hard coated for Scratch Proof (Hardness: 4H),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cover for Nook HD,Hd+ Cheetah Cover- Nook,0,Nook,">#85,661 in Computers & Accessories (See top 100)",Computers,2013-09-11,0594450284,[Cheetah cover],"{'Brand Name': 'Nook', 'Item Weight': '1 pound...",NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#Clean rank
meta_data['rank']=meta_data['rank'].apply(lambda x: x.split('in',1)[0] if isinstance(x,str) else 0)
meta_data.head()

,description,title,image,brand,rank,main_cat,date,asin,feature,tech1,also_buy,price,also_view,tech2,details,similar_item
0,Brand new. Still in factory-sealed plastic.,Kelby Training DVD: The Adobe Photoshop CS5 7-...,1,Kelby Training,">#654,681",Computers,2011-12-02,0321732960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,If you're already a Photoshop user and want a ...,Kelby Training DVD: Adobe Photoshop CS5 Power ...,1,Kelby Training,">#830,165",Computers,2011-11-07,0321735722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,School To Home Notes: Note From the Teacher!\n...,TEACHERS FRIEND NOTE FROM THE TEACHER SCHOOL T...,1,TEACHERS FRIEND,">#1,233,887",Computers,2007-06-06,0439651859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dooqi is a young brand specializing in high-en...,"[3-pack]Ipad Mini Screen Protector, Dooqi Scre...",1,dooqi,">#454,595",Computers,2014-12-05,0545729971,"[Hard coated for Scratch Proof (Hardness: 4H),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cover for Nook HD,Hd+ Cheetah Cover- Nook,0,Nook,">#85,661",Computers,2013-09-11,0594450284,[Cheetah cover],"{'Brand Name': 'Nook', 'Item Weight': '1 pound...",NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
for crc in ['>','#',',']:
    meta_data['rank']=meta_data['rank'].apply(lambda x:x.replace(crc,'') if isinstance(x,str) else 0)
meta_data.head()

,description,title,image,brand,rank,main_cat,date,asin,feature,tech1,also_buy,price,also_view,tech2,details,similar_item
0,Brand new. Still in factory-sealed plastic.,Kelby Training DVD: The Adobe Photoshop CS5 7-...,1,Kelby Training,654681,Computers,2011-12-02,0321732960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,If you're already a Photoshop user and want a ...,Kelby Training DVD: Adobe Photoshop CS5 Power ...,1,Kelby Training,830165,Computers,2011-11-07,0321735722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,School To Home Notes: Note From the Teacher!\n...,TEACHERS FRIEND NOTE FROM THE TEACHER SCHOOL T...,1,TEACHERS FRIEND,1233887,Computers,2007-06-06,0439651859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dooqi is a young brand specializing in high-en...,"[3-pack]Ipad Mini Screen Protector, Dooqi Scre...",1,dooqi,454595,Computers,2014-12-05,0545729971,"[Hard coated for Scratch Proof (Hardness: 4H),...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Cover for Nook HD,Hd+ Cheetah Cover- Nook,0,Nook,85661,Computers,2013-09-11,0594450284,[Cheetah cover],"{'Brand Name': 'Nook', 'Item Weight': '1 pound...",NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#Filtering on the columns we want to use
meta_data=meta_data[['asin','date','title','description','image','main_cat','brand','rank']]

In [39]:
#Creating year column
meta_data['product_year']=meta_data['date'].dt.year
meta_data['product_year']=meta_data['product_year'].fillna(-1)
meta_data['product_year']=meta_data['product_year'].astype(int)

In [40]:
meta_data['product_year'].value_counts(dropna=False)

 2016    5530
 2015    4024
 2014    2259
 2013    1837
 2012    1447
 2017    1193
 2011     484
 2010     433
 2009     220
 2008     200
-1        184
 2007     159
 2002     159
 2004     132
 2006     126
 2018     100
 2003      94
 2001      88
 2005      71
 1999      24
 2000       4
 1973       2
 2019       1
 1994       1
Name: product_year, dtype: int64

In [41]:
meta_data.head()

,asin,date,title,description,image,main_cat,brand,rank,product_year
0,0321732960,2011-12-02,Kelby Training DVD: The Adobe Photoshop CS5 7-...,Brand new. Still in factory-sealed plastic.,1,Computers,Kelby Training,654681,2011
1,0321735722,2011-11-07,Kelby Training DVD: Adobe Photoshop CS5 Power ...,If you're already a Photoshop user and want a ...,1,Computers,Kelby Training,830165,2011
2,0439651859,2007-06-06,TEACHERS FRIEND NOTE FROM THE TEACHER SCHOOL T...,School To Home Notes: Note From the Teacher!\n...,1,Computers,TEACHERS FRIEND,1233887,2007
3,0545729971,2014-12-05,"[3-pack]Ipad Mini Screen Protector, Dooqi Scre...",Dooqi is a young brand specializing in high-en...,1,Computers,dooqi,454595,2014
4,0594450284,2013-09-11,Hd+ Cheetah Cover- Nook,Cover for Nook HD,0,Computers,Nook,85661,2013

In [42]:
meta_data.shape

(18772, 9)

In [43]:
#Dropping duplicates
meta_data.drop_duplicates(subset=['asin','title'], inplace=True)
meta_data.shape

(18521, 9)

# Appliances Reviews Dataset Cleaning

In [45]:
df_appliances.head()

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"08 22, 2013",A34A1UP40713F8,B00009W3I4,{'Style:': ' Dryer Vent'},James. Backus,I like this as a vent as well as something tha...,Great product,1377129600,NaN,NaN
1,5,True,"02 8, 2016",A1AHW6I678O6F2,B00009W3PA,{'Size:': ' 6-Foot'},kevin.,good item,Five Stars,1454889600,NaN,NaN
2,5,True,"08 5, 2015",A8R48NKTGCJDQ,B00009W3PA,{'Size:': ' 6-Foot'},CDBrannom,Fit my new LG dryer perfectly.,Five Stars,1438732800,NaN,NaN
3,5,True,"04 24, 2015",AR3OHHHW01A8E,B00009W3PA,{'Size:': ' 6-Foot'},Calvin E Reames,Good value for electric dryers,Perfect size,1429833600,NaN,NaN
4,5,True,"03 21, 2015",A2CIEGHZ7L1WWR,B00009W3PA,{'Size:': ' 6-Foot'},albert j. kong,Price and delivery was excellent.,Five Stars,1426896000,NaN,NaN

In [48]:
#Filling N/A in vote column
df_appliances['vote']=df_appliances['vote'].fillna(0)
df_appliances['vote']=df_appliances['vote'].apply(lambda x: x.replace(',','') if isinstance(x,str) else x)

In [54]:
df_appliances['review_date']=df_appliances['unixReviewTime'].apply(lambda x:datetime.datetime.utcfromtimestamp(x).strftime('%Y-%m-%d'))

In [55]:
df_appliances.head()

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image,review_timestamp,review_date
0,5,True,"08 22, 2013",A34A1UP40713F8,B00009W3I4,{'Style:': ' Dryer Vent'},James. Backus,I like this as a vent as well as something tha...,Great product,1377129600,0,NaN,2013-08-22,2013-08-22
1,5,True,"02 8, 2016",A1AHW6I678O6F2,B00009W3PA,{'Size:': ' 6-Foot'},kevin.,good item,Five Stars,1454889600,0,NaN,2016-02-08,2016-02-08
2,5,True,"08 5, 2015",A8R48NKTGCJDQ,B00009W3PA,{'Size:': ' 6-Foot'},CDBrannom,Fit my new LG dryer perfectly.,Five Stars,1438732800,0,NaN,2015-08-05,2015-08-05
3,5,True,"04 24, 2015",AR3OHHHW01A8E,B00009W3PA,{'Size:': ' 6-Foot'},Calvin E Reames,Good value for electric dryers,Perfect size,1429833600,0,NaN,2015-04-24,2015-04-24
4,5,True,"03 21, 2015",A2CIEGHZ7L1WWR,B00009W3PA,{'Size:': ' 6-Foot'},albert j. kong,Price and delivery was excellent.,Five Stars,1426896000,0,NaN,2015-03-21,2015-03-21

In [59]:
df_appliances['review_date']=df_appliances['review_date'].astype('datetime64')
df_appliances['review_date'].dtype

dtype('<M8[ns]')

In [60]:
df_appliances['review_date']

0      2013-08-22
1      2016-02-08
2      2015-08-05
3      2015-04-24
4      2015-03-21
          ...
2272   2016-12-06
2273   2016-03-20
2274   2016-10-15
2275   2016-01-05
2276   2016-12-05
Name: review_date, Length: 2277, dtype: datetime64[ns]

In [63]:
#Filtering and reordering columns

df_appliances=df_appliances[['asin','review_date','reviewerID','reviewerName','summary','overall','reviewText','vote']]
df_appliances.head()

,asin,review_date,reviewerID,reviewerName,summary,overall,reviewText,vote
0,B00009W3I4,2013-08-22,A34A1UP40713F8,James. Backus,Great product,5,I like this as a vent as well as something tha...,0
1,B00009W3PA,2016-02-08,A1AHW6I678O6F2,kevin.,Five Stars,5,good item,0
2,B00009W3PA,2015-08-05,A8R48NKTGCJDQ,CDBrannom,Five Stars,5,Fit my new LG dryer perfectly.,0
3,B00009W3PA,2015-04-24,AR3OHHHW01A8E,Calvin E Reames,Perfect size,5,Good value for electric dryers,0
4,B00009W3PA,2015-03-21,A2CIEGHZ7L1WWR,albert j. kong,Five Stars,5,Price and delivery was excellent.,0

# Joining the data

In [65]:
df=df_appliances.merge(meta_data, how='left', on='asin')
df.head()

,asin,review_date,reviewerID,reviewerName,summary,overall,reviewText,vote,date,title,description,image,main_cat,brand,rank,product_year
0,B00009W3I4,2013-08-22,A34A1UP40713F8,James. Backus,Great product,5,I like this as a vent as well as something tha...,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B00009W3PA,2016-02-08,A1AHW6I678O6F2,kevin.,Five Stars,5,good item,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,B00009W3PA,2015-08-05,A8R48NKTGCJDQ,CDBrannom,Five Stars,5,Fit my new LG dryer perfectly.,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B00009W3PA,2015-04-24,AR3OHHHW01A8E,Calvin E Reames,Perfect size,5,Good value for electric dryers,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,B00009W3PA,2015-03-21,A2CIEGHZ7L1WWR,albert j. kong,Five Stars,5,Price and delivery was excellent.,0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
df_appliances.tail()

,asin,review_date,reviewerID,reviewerName,summary,overall,reviewText,vote
2272,B0006GVNOA,2016-12-06,A2B2JVUX5YN8RU,Caleb,Worked like a charm,5,Works great. I used it and an extension kit wi...,6
2273,B0006GVNOA,2016-03-20,A1IT56MV1C09VS,Looneypenguin,Excellent product and showed me that my vent o...,5,Anyone who thinks they don't have a problem wi...,5
2274,B00570RQ0A,2016-10-15,A13391AZAFJ67K,Fred A,Five Stars,5,good,0
2275,B00570RQ0A,2016-01-05,A2V0JXLJ9VCNNX,Amazon Customer,Five Stars,5,washer washing,0
2276,B00W4YKCGC,2016-12-05,A3GP2HMB2AFOKF,Juan,Five Stars,5,Great product fast shipping,0

In [69]:
meta_data['asin'].tail(10)

18762    B01HI5CVK6
18763    B01HI59IJI
18764    B01HI47Y9K
18765    B01HI6N9LA
18766    B01HI76P24
18767    B01HI72XZW
18768    B01HIEI83Q
18769    B01HIQYNJM
18770    B01HIWBL46
18771    B01HJ49FSW
Name: asin, dtype: object

In [68]:
df_appliances['asin'].head(10)

0    B00009W3I4
1    B00009W3PA
2    B00009W3PA
3    B00009W3PA
4    B00009W3PA
5    B00009W3PA
6    B0009GVYNW
7    B000N6302Q
8    B000N6302Q
9    B000N6302Q
Name: asin, dtype: object

In [71]:
df_beauty.head()

,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,5,True,"09 1, 2016",A3CIUOJXQ5VDQ2,B0000530HU,"{'Size:': ' 7.0 oz', 'Flavor:': ' Classic Ice ...",Shelly F,As advertised. Reasonably priced,Five Stars,1472688000,NaN,NaN
1,5,True,"11 14, 2013",A3H7T87S984REU,B0000530HU,"{'Size:': ' 7.0 oz', 'Flavor:': ' Classic Ice ...",houserules18,Like the oder and the feel when I put it on my...,Good for the face,1384387200,NaN,NaN
2,1,True,"08 18, 2013",A3J034YH7UG4KT,B0000530HU,"{'Size:': ' 7.0 oz', 'Flavor:': ' Classic Ice ...",Adam,I bought this to smell nice after I shave. Wh...,Smells awful,1376784000,NaN,NaN
3,5,False,"05 3, 2011",A2UEO5XR3598GI,B0000530HU,"{'Size:': ' 7.0 oz', 'Flavor:': ' Classic Ice ...",Rich K,HEY!! I am an Aqua Velva Man and absolutely lo...,Truth is There IS Nothing Like an AQUA VELVA MAN.,1304380800,25,NaN
4,5,True,"05 6, 2011",A3SFRT223XXWF7,B00006L9LC,{'Size:': ' 200ml/6.7oz'},C. C. Christian,If you ever want to feel pampered by a shampoo...,Bvlgari Shampoo,1304640000,3,NaN

In [76]:
#os.mkdir('../data/exports')
df_appliances.to_excel('../data/exports/appliances.xlsx')

In [77]:
meta_data.to_excel('../data/exports/meta_data.xlsx')